runtime: nodejs20
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 2
handlers:
  - url: /
    static_files: dist/my-angular-app/index.html
    upload: dist/my-angular-app/index.html
  - url: /
    static_dir: dist/my-angular-app
