name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        working-directory: ./my-angular-app/
        run: npm install

      - name: Build Angular app for production
        working-directory: ./my-angular-app/
        run: npm run build -- --configuration=production

      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: dist-${{ github.run_number }}-${{ github.run_id }}-${{ github.sha }}-${{ github.event_name }}-${{ github.event.created_at }}
          path: ./my-angular-app/dist/my-angular-app

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to App Engine
        run: |
          gcloud app deploy ./my-angular-app/dist/my-angular-app/app.yaml --project=${{ secrets.GCP_PROJECT_ID }} --quiet --promote
